name: Output Information
on: 
 pull_request:
  types:
   - opened
 workflow_dispatch: 
 push:
  branches:
    - main
    - 'dev-*'
    - 'feat/**'
  paths-ignore: 
    - '.github/workfllows/*'
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Output event data
     run: echo "${{ toJSON(github.event) }}"
   - name: Get Code
     uses: actions/checkout@v3
   - name: Install Dependencies
     run: npm ci
   - name: Test code
     run: npm run test
   - name: Build Project
     run: npm run build
   - name: Deploy Project
     run: echo "Deploying..."